menu:
 Archive: archives/
 About: about/
 3D Printing: categories/3d-printing-definition/
 The Future: categories/the-future/
 Trending Tech: categories/trending-tech/
 3D Resources: categories/3d-resources/
 Recommended 2019: categories/recommended-2019/

widgets:
 - greeting
 - site_links

rss: /atom.xml

readMore: ...read more

feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:

tag_generator:
  per_page: 10
